export const primaryColors = {
  LightPurple: "#dfdbff",
  Purple: "#8a4bf2",
  // Purple: "#60A5FA",
  // Purple: "#fff",
  black: "#000",
  White: "#fff",
  Gray: "#F8F8F8",
  Green: "#1cd086",
  mintGreen: "#D8F8E9",
  DashBoardBackground: "#f8f7ff",
  Red: "#ff0000",
  Blue: "#000dfd",
  Yellow: "#ffe600",
  Grey: "#EBEBEB",
};
